### ISSUE TITLE
Build failed because two lint jobs ran simultaneously

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#166]
**Describe the bug**

This requires more triaging since the builds should not be sharing any directories but [build 1355](https://buildkite.com/opstrace/scheduled-main-builds/builds/1355#ed9dcab4-3c5a-4c15-bece-57df9ba24626/1532-1630) failed with:

```
[2020-12-12T20:10:08Z] (cd go/ && golangci-lint run)
[2020-12-12T20:10:13Z] ERRO Parallel golangci-lint is running
```

[Build 3271](https://buildkite.com/opstrace/prs/builds/3271#3fb10326-e962-4c2b-92ec-29d4fb13ace4/1594-1689) was running the lint job at the same time:

```
[2020-12-12T20:10:07Z] (cd go/ && golangci-lint run)
[2020-12-12T20:10:16Z] make[1]: Leaving directory '/build'
```

**Comment by jgehrcke** [comment]
Huh. Indeed, there should be "proper" isolation with respect to the build directories, but /tmp is generally as of now intentionally shared across all builds.

Maybe golangci-lint uses a specific lock file in /tmp managed by itself (so that it does not run "on the same code base" concurrently)?

**Comment by jgehrcke** [comment]
`--allow-parallel-runners`:

> Allow multiple parallel golangci-lint instances running. If false (default) - golangci-lint acquires file lock on start.

https://golangci-lint.run/usage/configuration/

**Comment by jgehrcke** [comment]
Also... lock file management is -- as we know -- always to be done with extreme caution, and not every program does that. https://github.com/golangci/golangci-lint/issues/1021.

**Comment by sreis** [comment]
>  but /tmp is generally as of now intentionally shared across all builds.

I never noticed we were sharing `/tmp` before in the CI builds. Thank you for bringing it up.

BTW, why did you choose [this approach](https://github.com/opstrace/opstrace/blob/main/Makefile#L367-L383) instead of defining where the [build logs are with relative paths](https://buildkite.com/docs/pipelines/artifacts#uploading-artifacts-in-build-steps)? What's the advantage of copying everything over to a dir in `/tmp`?

**Comment by jgehrcke** [comment]
> I never noticed we were sharing /tmp before in the CI builds. Thank you for bringing it up.

Yes. A little bit of clarification: `/tmp` on the host was/is in my mental modal _the_ central place for sharing state between host and individual containers, and also between individual containers: we mount the host's `/tmp` into each container at `/tmp`, and in addition to that we also mount the "build dir" (which is below `/tmp` on the host) into a container under `/build`.

> What's the advantage of copying everything over to a dir in /tmp?

This has little/nothing to do with collecting build artifacts.

The central idea was /is that every `make ci-...` invocation actually _can_ get its own "sandbox" (trough the `OPSTRACE_BUILD_DIR` concept). 

`OPSTRACE_BUILD_DIR` is what "everything" gets copied to, and which is what is after all also set as`$HOME` in the container invoked by `make `ci--...`.

That's the mechanism how `main-test-gcp` and `main-test-aws` do _not_ run in the same directory and can both use `$HOME/.kube` etc w/o interfering with each other.

Real-world examples from the same BK build:

```
[2020-12-14T08:53:46Z] OPSTRACE_CLUSTER_NAME is bk-1365-4ab-a
[2020-12-14T08:53:46Z] OPSTRACE_BUILD_DIR is /tmp/opstrace-bk-1365-4ab9886-1-aws
```

```
[2020-12-14T08:21:01Z] OPSTRACE_CLUSTER_NAME is bk-1365-4ab-g
[2020-12-14T08:21:01Z] OPSTRACE_BUILD_DIR is /tmp/opstrace-bk-1365-4ab9886-1-gcp
```

The source of the rsync-based copying is the "prebuild dir" which is what the preamble step leaves behind. Think: the preamble prepares a certain state, and subsequent jobs can consume that state and _mutate it_ w/o disturbing each other.

So much for the theory and historical evolution :).

**Comment by jgehrcke** [comment]
I think this is now resolved via #228.

**Comment by MatApple** [comment]
I believe we're still seeing this issue: https://buildkite.com/opstrace/prs/builds/4376#57bdfe0a-97ad-4a59-ac96-7eec8bda6623
```

[2021-05-28T14:28:57Z]  \|   297:5  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion
--
&nbsp; | [2021-05-28T14:28:57Z]  \|   306:5  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion
&nbsp; | [2021-05-28T14:28:57Z]  \|   315:5  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion
&nbsp; | [2021-05-28T14:28:57Z]  \|
&nbsp; | [2021-05-28T14:28:57Z]  \| /build/lib/kubernetes/src/reconciliation/reconcile.ts
&nbsp; | [2021-05-28T14:28:57Z]  \|   215:11  warning  '_pvc' is defined but never used  @typescript-eslint/no-unused-vars
&nbsp; | [2021-05-28T14:28:57Z]  \|
&nbsp; | [2021-05-28T14:28:57Z]  \| ✖ 27 problems (0 errors, 27 warnings)
&nbsp; | [2021-05-28T14:28:57Z]  \|
&nbsp; | Done in 73.55s.
&nbsp; | [2021-05-28T14:28:57Z] # Also see https://github.com/opstrace/opstrace/issues/166
&nbsp; | [2021-05-28T14:28:57Z] (cd go/ &amp;&amp; golangci-lint run --allow-parallel-runners)
&nbsp; | [2021-05-28T14:29:57Z] ERRO Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded
&nbsp; | [2021-05-28T14:29:57Z] ERRO Timeout exceeded: try increasing it by passing --timeout option
&nbsp; | [2021-05-28T14:29:58Z] make[1]: *** [Makefile:236: lint-codebase.go] Error 4
&nbsp; | [2021-05-28T14:29:58Z] make[1]: Leaving directory '/build'
&nbsp; | [2021-05-28T14:29:58Z] make: *** [Makefile:740: preamble] Error 2
&nbsp; | [2021-05-28T14:29:59Z] make: *** [ci-preamble] Error 2
&nbsp; | [2021-05-28T14:29:59Z] 🚨 Error: The command exited with status 2


```

**Comment by MatApple** [comment]
@jgehrcke @sreis  is this the same error ^?

**Comment by sreis** [comment]
@MatApple looks like a different problem. This looks like some network timeout.

```
[2021-05-28T14:29:57Z] ERRO Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded
```

**Comment by jgehrcke** [comment]
@MatApple @sreis and the problem seen by Mat is tracked here: https://github.com/opstrace/opstrace/issues/709 -- I am carrying this over.

**Comment by MatApple** [comment]
Ok thank you
